const KEY='pet-study-v1';
const defaults={version:1,settings:{name:'茉莉',exam:'2026-10-17',goal:'通过 PET',minutes:[60,35,35,35,35,35,60]},days:{},mistakes:{},drafts:{},custom:[]};
let state=structuredClone(defaults),storageError=false;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(valid(parsed))state=parsed;else storageError=true;}}catch{storageError=true;}
function valid(s){return s?.version===1&&typeof s.settings?.name==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s.settings.exam)&&Array.isArray(s.settings.minutes)&&s.settings.minutes.length===7&&s.settings.minutes.every(n=>Number.isInteger(n)&&n>=0&&n<=180)&&s.days&&typeof s.days==='object'&&!Array.isArray(s.days)&&Object.values(s.days).every(d=>Array.isArray(d.done)&&Array.isArray(d.tasks))&&s.mistakes&&typeof s.mistakes==='object'&&s.drafts&&typeof s.drafts==='object'&&Array.isArray(s.custom);}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dayKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('保存失败，请在家长空间导出备份');return false;}}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',3500);}
const questions=[
{id:'r1',text:'Library notice: Please return all books by Friday. The library will be closed next week for repairs.',prompt:'What should students do?',options:['Bring their books back before the library closes.','Collect new books from the library next week.','Help repair the library on Friday.'],answer:0,explain:'return all books by Friday 表示最迟周五归还。next week 关闭是归还截止时间的原因。'},
{id:'r2',text:'Mia: I have two tickets for Saturday’s concert. My sister can’t come. Would you like to join me?',prompt:'Why is Mia sending this message?',options:['To cancel a concert.','To invite someone to use a spare ticket.','To ask someone to buy two tickets.'],answer:1,explain:'姐姐不能去，因此 Mia 邀请对方使用多出的一张票。'},
{id:'r3',text:'Swimming pool: Children under twelve must be accompanied by an adult.',prompt:'Who needs to come with an adult?',options:['All visitors.','Only children aged twelve.','Children younger than twelve.'],answer:2,explain:'under twelve 指未满十二岁。accompanied by 表示由某人陪同。'},
{id:'r4',text:'Sam: The bus is late. Please start lunch without me. I’ll get something on the way.',prompt:'What does Sam want his friends to do?',options:['Eat before he arrives.','Wait for him at the bus stop.','Buy him some lunch.'],answer:0,explain:'start lunch without me 是请朋友先吃；Sam 会在路上自己买吃的。'},
{id:'r5',text:'Lost property: Items left here for more than one month will be donated to charity.',prompt:'What happens to items that nobody collects?',options:['They are sold after a week.','They are given away after a month.','They are kept here forever.'],answer:1,explain:'more than one month 为超过一个月，donated to charity 指捐赠给慈善机构。'}];
function ensureDay(){const k=dayKey();if(!state.days[k]){const budget=state.settings.minutes[new Date().getDay()];const tasks=[];let left=budget;const choices=[{id:'read',kind:'阅读',title:'短消息阅读练习',detail:'5 道原创练习，做完查看解释。',minutes:10},{id:'write',kind:'写作',title:'给朋友写一封邮件',detail:'回应邀请，说明安排，再提出一个问题。',minutes:15},{id:'speak',kind:'口语',title:'说说你喜欢的活动',detail:'准备一分钟，再用英语说出理由和一个例子。',minutes:5}];if(Object.keys(state.mistakes).length)choices.unshift({id:'review',kind:'复习',title:'再试一次错题',detail:'先自己作答，再核对思路。',minutes:5});for(const task of choices){if(left>=task.minutes){tasks.push(task);left-=task.minutes;}}if(!tasks.length&&budget>0)tasks.push({id:'speak',kind:'口语',title:'用英语说说今天',detail:'说一件今天发生的事。',minutes:Math.min(5,budget)});state.days[k]={tasks,done:[]};save();}return state.days[k];}
const app=document.querySelector('#app');let view='today';
function render(){view=location.hash.slice(1)||'today';if(!['today','review','progress','parent'].includes(view))view='today';const day=ensureDay();const tabs='<nav class="tabs" aria-label="学习导航">'+[['today','今天'],['review','错题复习'],['progress','我的进度']].map(([v,l])=>`<a href="#${v}" class="${view===v?'active':''}">${l}</a>`).join('')+'</nav>';app.innerHTML=storageError?'<p class="notice">本机记录未能读取。请先导出或保留原备份，再继续使用。</p>':'';if(view==='parent'){renderParent();return;}app.innerHTML+=`<section class="intro"><div><div class="date">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</div><h1>${esc(state.settings.name)}，${view==='today'?'今天从这里开始':view==='review'?'再试一次':'每一步都算数'}</h1><p class="summary">${view==='today'?`今天 ${day.tasks.length} 项 · 约 ${day.tasks.reduce((n,t)=>n+t.minutes,0)} 分钟`:'按自己的节奏，继续往前。'}</p></div><div class="progress"><div class="ring" style="--pct:${day.tasks.length?day.done.length/day.tasks.length*100:0}%"><span>${day.done.length}/${day.tasks.length}</span></div><div class="muted">今日完成</div></div></section>${tabs}`;if(view==='today'){app.innerHTML+=day.tasks.length?day.tasks.map((t,i)=>`<article class="task ${day.done.includes(t.id)?'done':''}"><div class="number">${day.done.includes(t.id)?'✓':String(i+1).padStart(2,'0')}</div><div><span class="tag">${esc(t.kind)} · ${t.minutes} 分钟</span><h2>${esc(t.title)}</h2><p>${esc(t.detail)}</p></div><div class="actions"><button data-start="${esc(t.id)}">${day.done.includes(t.id)?'再看看':'开始'}</button>${day.done.includes(t.id)?`<button class="quiet" data-undo="${esc(t.id)}">撤销完成</button>`:''}</div></article>`).join(''):'<p class="empty">今天是休息日。</p>';if(day.tasks.length&&day.done.length===day.tasks.length)app.innerHTML+='<p class="complete celebrate">今天的任务完成了，可以安心休息。</p>';app.innerHTML+='<p class="source">起步练习 · 原创内容，非官方真题</p>';}else if(view==='review'){const ids=Object.keys(state.mistakes).filter(id=>questions.some(q=>q.id===id));app.innerHTML+=ids.length?ids.map(id=>`<article class="task"><div class="number">↻</div><div><h2>${esc(questions.find(q=>q.id===id).prompt)}</h2><p>答错 ${state.mistakes[id].count} 次 · ${esc(state.mistakes[id].date)}</p></div><button data-question="${id}">重做</button></article>`).join(''):'<p class="empty">还没有待复习的错题。阅读练习中的错题会保存在这里。</p>';}else{const days=Object.entries(state.days).sort(([a],[b])=>b.localeCompare(a));app.innerHTML+='<h2>学习记录</h2>'+days.slice(0,30).map(([d,v])=>`<div class="dayrow"><span>${esc(d)}</span><span>${v.done.length} / ${v.tasks.length} 项完成</span></div>`).join('')+'<p class="muted">完成记录不代表考试分数。</p>';}}
function finish(id){const day=ensureDay();if(!day.done.includes(id))day.done.push(id);save();document.querySelector('#exercise').close();render();toast('已记录，今天又完成了一项');}
function renderParent(){app.innerHTML+='<h1>家长空间</h1><p><a href="#today">返回孩子的今天</a></p><div class="notice">当前为本机试用版：记录保存在此浏览器。手机同步、自动推送和 AI 批改尚未接通。</div>'+`<form id="settings"><div class="grid"><label class="field">孩子称呼<input name="name" required maxlength="20" value="${esc(state.settings.name)}"></label><label class="field">考试日期<input name="exam" type="date" required value="${esc(state.settings.exam)}"></label></div><label class="field">目标<select name="goal">${['通过 PET','提高听读能力','提高写说能力'].map(s=>`<option ${state.settings.goal===s?'selected':''}>${s}</option>`).join('')}</select></label><h2>每天可学习时间</h2><div class="week">${[1,2,3,4,5,6,0].map(i=>`<label>周${'日一二三四五六'[i]}<input name="m${i}" type="number" min="0" max="180" required value="${state.settings.minutes[i]}" aria-label="周${'日一二三四五六'[i]}学习分钟"></label>`).join('')}</div><p class="muted">单位：分钟。0 表示休息；修改后用于新一天，已生成的任务保留。</p><button>保存安排</button></form><section class="section"><h2>添加今天的教材任务</h2><form id="custom"><label class="field">任务名称<input name="title" required maxlength="80" placeholder="例如：Complete Unit 8 阅读"></label><label class="field">材料位置与完成要求<input name="detail" required maxlength="200" placeholder="页码、题号、需要完成的内容"></label><label class="field">预计分钟<input name="minutes" type="number" min="1" max="120" value="10" required></label><button>添加到今天</button></form></section><section class="section"><h2>学习记录备份</h2><div class="actions"><button id="export">导出备份</button><label class="file">恢复备份<input type="file" id="import" accept="application/json,.json"></label></div><p class="muted">恢复会替换本机记录，操作前需要确认。备份含作文草稿，请自行保管。</p></section>`;}
let session=null;
function openTask(id){const task=ensureDay().tasks.find(t=>t.id===id);if(!task)return;if(id==='read'||id==='review'){const qs=id==='review'?questions.filter(q=>state.mistakes[q.id]):questions;session={id,qs,index:0,correct:0,answered:false};openQuestion();return;}document.querySelector('#exercise').showModal();const body=document.querySelector('#exerciseBody');body.innerHTML=`<span class="tag">${esc(task.kind)}</span><h2>${esc(task.title)}</h2><p>${esc(task.detail)}</p>`;if(id==='write'){body.innerHTML+='<p lang="en">Your friend Alex has invited you to a picnic on Saturday. Write an email to Alex: say whether you can come, suggest something to bring, and ask where to meet. Write about 100 words.</p><p class="source">原创练习，非官方真题</p>'+`<label class="field">你的邮件<textarea id="draft">${esc(state.drafts[dayKey()]||'')}</textarea></label><p id="words" class="muted"></p><p class="notice">AI 批改尚未接通。草稿自动保存在本机，可以请家长检查三个要点。</p><button id="finish" disabled>保存并完成</button>`;const update=()=>{const text=document.querySelector('#draft').value;state.drafts[dayKey()]=text;save();document.querySelector('#words').textContent=`${text.trim()?text.trim().split(/\s+/).length:0} words`;document.querySelector('#finish').disabled=!text.trim();};document.querySelector('#draft').addEventListener('input',update);update();}else if(id==='speak'){body.innerHTML+='<p lang="en">What do you enjoy doing after school? Who do you do it with? Why do you like it?</p><p>试着说出一项活动、一个理由和一个例子。说完可以请家长反馈。</p><p class="notice">当前为自主练习，AI 语音陪练尚未接通。</p><button id="finish">我练习完成了</button>';}else body.innerHTML+='<button id="finish">我完成了</button>';document.querySelector('#finish').onclick=()=>finish(id);}
function openQuestion(){const q=session.qs[session.index],body=document.querySelector('#exerciseBody');const modal=document.querySelector('#exercise');if(!modal.open)modal.showModal();if(!q){body.innerHTML=`<h2>这组练习完成了</h2><p>本次首次作答正确 ${session.correct} / ${session.qs.length} 题。</p><p>错题已记录，之后可以再练。</p><button id="finish">${session.id?'完成任务':'返回错题集'}</button>`;document.querySelector('#finish').onclick=()=>session.id?finish(session.id):(modal.close(),render());return;}session.answered=false;body.innerHTML=`<span class="tag">${session.index+1} / ${session.qs.length} · 原创阅读练习</span><h2 lang="en">${esc(q.prompt)}</h2><p lang="en">${esc(q.text)}</p><form id="answerForm"><div class="options">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" required><span lang="en">${String.fromCharCode(65+i)}. ${esc(o)}</span></label>`).join('')}</div><button>核对答案</button></form><div id="feedback"></div>`;document.querySelector('#answerForm').onsubmit=e=>{e.preventDefault();if(session.answered)return;session.answered=true;const chosen=Number(new FormData(e.target).get('answer'));const correct=chosen===q.answer;if(correct){session.correct++;delete state.mistakes[q.id];}else state.mistakes[q.id]={count:(state.mistakes[q.id]?.count||0)+1,date:dayKey()};save();e.target.querySelectorAll('input,button').forEach(el=>el.disabled=true);document.querySelector('#feedback').innerHTML=`<div class="feedback"><strong>${correct?'答对了':'正确答案是 '+String.fromCharCode(65+q.answer)}</strong><p>${esc(q.explain)}</p></div><button id="next">${session.index===session.qs.length-1?'查看结果':'下一题'}</button>`;document.querySelector('#next').onclick=()=>{session.index++;openQuestion();};};}
document.querySelector('#parentButton').onclick=()=>location.hash='parent';
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.start)openTask(b.dataset.start);if(b.dataset.undo){const d=ensureDay();d.done=d.done.filter(id=>id!==b.dataset.undo);save();render();}if(b.dataset.question){session={id:null,qs:[questions.find(q=>q.id===b.dataset.question)],index:0,correct:0};openQuestion();}if(b.id==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`pet-backup-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
app.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(e.target.id==='settings'){state.settings={name:f.get('name').trim()||'同学',exam:f.get('exam'),goal:f.get('goal'),minutes:Array.from({length:7},(_,i)=>Number(f.get('m'+i)))};save();toast('安排已保存');}if(e.target.id==='custom'){const d=ensureDay(),minutes=Number(f.get('minutes'));const total=d.tasks.reduce((s,t)=>s+t.minutes,0);if(total+minutes>state.settings.minutes[new Date().getDay()]&&!confirm('添加后将超过今天的学习时间，仍要添加吗？'))return;d.tasks.push({id:'custom-'+crypto.randomUUID(),kind:'教材',title:f.get('title').trim(),detail:f.get('detail').trim(),minutes});save();toast('已添加到今天');e.target.reset();}});
app.addEventListener('change',async e=>{if(e.target.id!=='import'||!e.target.files[0])return;try{const file=e.target.files[0];if(file.size>5000000)throw Error();const incoming=JSON.parse(await file.text());if(!valid(incoming))throw Error();if(confirm('用这份备份替换本机全部学习记录？')){state=incoming;save();render();toast('备份已恢复');}}catch{toast('无法恢复：备份格式不正确');}e.target.value='';});
window.addEventListener('hashchange',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!document.querySelector('#exercise').open)render();});
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
